export const ssc = [
  {
    isAttempted: false,
    finalScore: null,
    Mock: 1,
    questions: [
      {
        ques: 1,
        Question: "How many legs have in cockroach",
        a: 5,
        b: 6,
        c: 2,
        d: 4,
        ans: 6,
      },
      {
        ques: 2,
        Question: "How many legs have in cockroach",
        a: 5,
        b: 6,
        c: 2,
        d: 4,
        ans: 6,
      },
      {
        ques: 3,
        Question: "How many legs have in cockroach",
        a: 5,
        b: 6,
        c: 2,
        d: 4,
        ans: 6,
      },
      {
        ques: 4,
        Question: "How many legs have in cockroach",
        a: 5,
        b: 6,
        c: 2,
        d: 4,
        ans: 6,
      },
    ],
  },
];
